version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    pre_install:
      - git update-index --assume-unchanged .rtd-environment.yml docs/conf.py

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

formats:
  - htmlzip

conda:
  environment: rtd_environment.yml

# This part is necessary otherwise the project is not built
python:
   install:
      - method: pip
        path: .
