name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow rebuilds via API.
  repository_dispatch:
    types: rebuild

concurrency:
  group: run_tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            label: linux-64

          #- os: macos-latest
          #  label: osx-64
          #  prefix: /Users/runner/miniconda3/envs/my-env

          #- os: windows-latest
          #  label: win-64
          #  prefix: C:\Miniconda3\envs\my-env

    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Install Conda environment with Micromamba
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: kalpy_build
          miniforge-version: latest

      - name: Build kalpy
        env:
          KALDI_ROOT: ~/miniconda3/envs/kalpy_build
        shell: bash -l {0}
        run: pip install .

      - name: Run tests
        shell: bash -l {0}
        run: pytest -x ./tests
